# Site Settings
baseurl: "" # The subpath of website, e.g. /blog/
url: "https://anthonyvadala.me" # The base hostname & protocol for the site
plugins: [jekyll-paginate] # Include plugins
paginate: 5 # Sets items per page
paginate_path: /blog/page:num/ # Sets path of pages
permalink: /404.html # Sets 404 page
photo_embed: /images/profile_picture.jpg # Sets picture for Twitter Card/Open Graph

#Personal Settings
title: Anthony Vadala
email: personal@anthonyvadala.me
description: Hello, I'm Anthony Vadala! I am an aspiring network specialist and hobbyist web designer.
twitter_username: Anthony_Vadala
github_username: AnthonyVadala
linkedin_username: AnthonyVadala
keybase_username: anthonyvadala

#Header Text
header_text: Hello, I'm Anthony Vadala!
description_text: I am an aspiring network specialist and hobbyist web designer.